### ISSUE TITLE
Individual "HOSTING LINKS" are put in different parts of the Frontend, shift them to a .env file

### ISSUE THREAD

**Issue by whysosaket** [whysosaket/LinkMyLinks#7]

**Comment by dz-ai** [comment]
Hi can I go for it?

**Comment by chaitralikakde** [comment]
Please assign me this issue

**Comment by whysosaket** [comment]
okay @charu1603

**Comment by whysosaket** [comment]
@dz-ai you still up for this work?

**Comment by dz-ai** [comment]
Yes

**Comment by whysosaket** [comment]
@dz-ai Okay, go ahead

**Comment by dz-ai** [comment]
So now since I add an .env file which is not going to be push to github I guess it is up to you to add it to Netlify Environment Variables...

**Comment by dz-ai** [comment]
And the .env I will push as you did in server as .env.exemple

**Comment by whysosaket** [comment]
@dz-ai  Yeah, sure that would be ideal
