### ISSUE TITLE
Make a landing page

### ISSUE THREAD

**Issue by whysosaket** [whysosaket/LinkMyLinks#8]

**Comment by archiejain28** [comment]
Hi @whysosaket ,  I can work on this issue. Could you please give some more detail in brief about this?

**Comment by whysosaket** [comment]
Hey @archiejain28 You can make a homepage, which is shown to the user when they first land on the page, there you can add two buttons login/signup, which lead to the login and signup pages respectively.
you can use this image as a reference https://unbounce.com/photos/blog-visual-cta-2x-v2.jpg  , where the "Explore Templates" button can be replaced with a "Login" button, although you're free to apply your own ideas.

Also, try to use tailwindsCSS or make you can also use custom CSS of your own
